name: Pull Qdrant Image
on: workflow_dispatch

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull qdrant/qdrant:latest

      - name: Save image
        run: docker save qdrant/qdrant:latest > qdrant.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qdrant
          path: qdrant.tar
