name: Pull attu Image
on: workflow_dispatch

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull zilliz/attu:v2.6.3

      - name: Save image
        run: docker save zilliz/attu:v2.6.3 > attu.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: attu
          path: attu.tar
