name: Pull RustFS Image
on: workflow_dispatch

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull rustfs/rustfs:latest

      - name: Save image
        run: docker save rustfs/rustfs:latest > rustfs.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustfs
          path: rustfs.tar
